# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapad', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([]),
        ),
    ]
