# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapad', '0003_home_media_module_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='home',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
