# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0002_cours_module_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='url_media',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='url_media',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
