# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0002_auto_20170502_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='nb_module',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
