# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0003_auto_20170505_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='url_media',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url_media',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
