# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0006_auto_20170515_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='nb_module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
        migrations.AddField(
            model_name='cours',
            name='modules',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='escapad_formulaire.Module'),
            preserve_default=False,
        ),
    ]
