# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0007_auto_20170623_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='cours',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='escapad_formulaire.Cours'),
            preserve_default=False,
        ),
    ]
