# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0008_auto_20170623_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='id',
        ),
        migrations.AlterField(
            model_name='cours',
            name='url_home',
            field=models.CharField(max_length=30, primary_key=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
