# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad_formulaire', '0009_auto_20170623_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='cours',
            field=models.ManyToManyField(blank=True, to='escapad_formulaire.Cours'),
        ),
    ]
