# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapad', '0003_repository_show_feedback'),
        ('escapad_formulaire', '0010_auto_20170623_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='repositories',
            field=models.ManyToManyField(to='escapad.Repository'),
        ),
    ]
